/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BentoRiverOfNews {
    'items': Array<any>;
    'title': string;
  }
  interface BentoRiverOfNewsAttributes extends StencilHTMLAttributes {
    'items'?: Array<any>;
    'title'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BentoRiverOfNews': Components.BentoRiverOfNews;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'bento-river-of-news': Components.BentoRiverOfNewsAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLBentoRiverOfNewsElement extends Components.BentoRiverOfNews, HTMLStencilElement {}
  var HTMLBentoRiverOfNewsElement: {
    prototype: HTMLBentoRiverOfNewsElement;
    new (): HTMLBentoRiverOfNewsElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'bento-river-of-news': HTMLBentoRiverOfNewsElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'bento-river-of-news': HTMLBentoRiverOfNewsElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
